Disable checkbox and text field, hides Delete
Disables checkbox which appears grey now, text field is not editable,
but does not appear greyed out. Delete button is gone for current user.
However, gets an error on update: "NoMethodError in
Hydramata::GroupsController#update -- undefined method `[]' for
nil:NilClass"

HYDRASIR-290 #closes

Starting disabled check box workaround

HYDRASIR-290

Fixes post problem and changes UI look

Sends check box value via hidden field.
Hides current user's border

HYDRASIR-12 #close

Change to allow setting group membership on group creation page

Revert "Change to allow setting group membership on group creation page"

This reverts commit cb563166a18e50210c8ee6f1f19dc93437ebfd05.

Resolves Rubydora reload and API problem with deletes (soft and hard).

With the upgrade of Rubydora from 1.6.5 to 1.7.0 they switched to an
API approach to method calls.  We had to adjust the monkey patch to
account for this.

They removed the automatic reload after actions in Fedora.  We had
to adjust the with_generic_file controller to use a before action.

HYDRASIR-237 #close

Update UI for editing group membership

Change "Title" to "Group Name". Change the "manager?" checkbox for each item to
a column with the heading "Can edit group". Use bootstrap '.row' and '.spanX'
classes to position elements correctly. Reformat HTML.

Add/Remove edit permissions for work

Add spec for add/remove works for Person

Changes to the autocomplete javascript to make it work with multiple autocompletes in one view. This fixes the issue of the first autcomplete input being selected after an autocomplete select

Depositor should not be deleted from the editor field

User should be able to add editors while creating work

Modify generator to copy predicate_mapping

Update specs