Array#wrap of multi-value input collection
Resolves the following:
    NoMethodError: undefined method `each_with_index' for nil:NilClass
      multi_value_input.rb:14:

Removing MultiValueWithElements input
  * This is something that may need to be tackled later, but for now
    it needs to go as it is interfering with specs